#!/usr/bin/env node

'use strict';

const path = require('path');

const ClientHook = require('../lib/ClientHook.js');

const hookName = path.basename(__filename);

const cwd = process.cwd();

const argv = process.argv;

const clientHook = new ClientHook({ hookName, cwd, argv });

clientHook.start();
